//
//  NewGame.swift
//  Goal
//
//  Created by Brett Moxey on 7/8/2023.
//

import Foundation


func getName() -> (firstName:String, surName:String, isMale:Bool, color:Int) {
    struct Surnames {
        var surname: String
        var light: Int
        var medLight: Int
        var medium: Int
        var medDark: Int
        var dark: Int
    }
    
    var surnames: [Surnames] = [
    Surnames(surname: "Adams", light: 30, medLight: 30, medium: 30, medDark: 5, dark: 5),
    Surnames(surname: "Allen", light: 30, medLight: 50, medium: 20, medDark: 0, dark:0),
    Surnames(surname: "Anderson", light: 30, medLight: 50, medium: 20, medDark: 0, dark: 0),
    Surnames(surname: "Bailey", light: 50, medLight:30, medium: 20, medDark: 0, dark: 0),
    Surnames(surname: "Bell", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Bennet", light: 30, medLight: 30, medium: 40, medDark: 0, dark: 0),
    Surnames(surname: "Blackman", light: 5,medLight:5, medium: 5, medDark: 5, dark: 80),
    Surnames(surname: "Brown", light: 5,medLight:5, medium: 5, medDark: 80, dark: 5),
    Surnames(surname: "Cameron", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Campbell", light: 30, medLight: 30, medium: 20, medDark: 10, dark: 10),
    Surnames(surname: "Carter", light: 30, medLight: 20, medium: 30, medDark: 10, dark: 10),
    Surnames(surname: "Chapman", light: 30, medLight: 30, medium: 30, medDark: 5, dark: 5),
    Surnames(surname: "Clarke", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Cooper", light: 40, medLight: 20, medium: 30, medDark: 0, dark: 10),
    Surnames(surname: "Davies", light: 30, medLight: 20, medium: 30, medDark: 10, dark: 10),
    Surnames(surname: "Dixon", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Doyle", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Dwyer", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Edwards", light: 30, medLight: 20, medium: 30, medDark: 10, dark: 10),
    Surnames(surname: "Elliot", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Ellis", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Evans", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Ferguson", light: 30, medLight: 30, medium: 40, medDark: 0, dark: 0),
    Surnames(surname: "Fisher", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Ford", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Foster", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Fox", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Fraser", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Freeman", light: 30, medLight: 30, medium: 30, medDark: 0, dark: 10),
    Surnames(surname: "Gibson", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Gill", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Gordon", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Graham", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Gray", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Green", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Hamilton", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Harrison", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Hart", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Hayes", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Henderson", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Hill", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Holmes", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Howard", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Huang", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0),
    Surnames(surname: "Hunter", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Irwin", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Jackson", light: 20, medLight: 10, medium: 20, medDark: 20, dark: 30),
    Surnames(surname: "Jenkins", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Johnson", light: 20, medLight: 30, medium: 20, medDark: 0, dark: 30),
    Surnames(surname: "Johnston", light: 20, medLight: 30, medium: 20, medDark: 0, dark: 30),
    Surnames(surname: "Jones", light: 30, medLight: 30, medium: 30, medDark: 0, dark: 10),
    Surnames(surname: "Kelly", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Kennedy", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "King", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Knight", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Lee", light: 10, medLight: 0, medium: 40, medDark: 40, dark: 10),
    Surnames(surname: "Lewis", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Lowe", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Lynch", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Martin", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Mason", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Matthews", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "McDonald", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Mills", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Mitchell", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Murphy", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Murray", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Nelson", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Newton", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Nguyen", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0),
    Surnames(surname: "Nicholson", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "O’Brien", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Parker", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Parsons", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Payne", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Pearce", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Phillips", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Power", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Price", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Reynolds", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Roberts", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Robinson", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Ross", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Ryan", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Scott", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Sharma", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0),
    Surnames(surname: "Simpson", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Smith", light: 30, medLight: 30, medium: 30, medDark: 10, dark: 0),
    Surnames(surname: "Spencer", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Stephens", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Taylor", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Thomas", light: 30, medLight: 40, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Tran", light: 0, medLight: 0, medium: 0, medDark: 50, dark: 0),
    Surnames(surname: "Turner", light: 40, medLight: 30, medium: 30, medDark: 0, dark: 0),
    Surnames(surname: "Wang", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0),
    Surnames(surname: "Webb", light: 40, medLight: 20, medium: 40, medDark: 0, dark: 0),
    Surnames(surname: "White", light: 10, medLight: 80, medium: 10, medDark: 0, dark: 0),
    Surnames(surname: "Xu", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0),
    Surnames(surname: "Young", light: 40, medLight: 20, medium: 40, medDark: 0, dark: 0),
    Surnames(surname: "Zhang", light: 0, medLight: 0, medium: 50, medDark: 50, dark: 0)]
    
    var boynames: [String] = [
    "Adam",
    "Aiden",
    "Alexander",
    "Ali",
    "Angus",
    "Archer",
    "Archie",
    "Ari",
    "Arlo",
    "Arthur",
    "Asher",
    "Ashton",
    "Austin",
    "Beau",
    "Benjamin",
    "Billy",
    "Bodhi",
    "Caleb",
    "Carter",
    "Charles",
    "Charlie",
    "Connor",
    "Cooper",
    "Daniel",
    "Darcy",
    "Dylan",
    "Edward",
    "Eli",
    "Elijah",
    "Ethan",
    "Ezra",
    "Felix",
    "Finn",
    "Fletcher",
    "Flynn",
    "Gabriel",
    "George",
    "Hamish",
    "Harrison",
    "Harry",
    "Harvey",
    "Henry",
    "Hudson",
    "Hugo",
    "Hunter",
    "Isaac",
    "Jack",
    "Jackson",
    "Jacob",
    "James",
    "Jasper",
    "Jaxon",
    "Jayden",
    "Jordan",
    "Joseph",
    "Joshua",
    "Jude",
    "Kai",
    "Lachlan",
    "Lennox",
    "Leo",
    "Leon",
    "Leonardo",
    "Levi",
    "Lewis",
    "Liam",
    "Lincoln",
    "Logan",
    "Louis",
    "Luca",
    "Lucas",
    "Luka",
    "Luke",
    "Marcus",
    "Mason",
    "Matthew",
    "Max",
    "Michael",
    "Muhammad",
    "Noah",
    "Oliver",
    "Oscar",
    "Owen",
    "Parker",
    "Patrick",
    "Riley",
    "River",
    "Ryan",
    "Ryder",
    "Samuel",
    "Sebastian",
    "Sonny",
    "Spencer",
    "Theo",
    "Theodore",
    "Thomas",
    "Vincent",
    "William",
    "Xavier",
    "Zachary"]
    
    var girlnames: [String] = [
    "Aaliyah",
    "Abigail",
    "Addison",
    "Adeline",
    "Alice",
    "Amelia",
    "Anna",
    "Annabelle",
    "Aria",
    "Ariana",
    "Audrey",
    "Aurora",
    "Ava",
    "Ayla",
    "Bella",
    "Billie",
    "Bonnie",
    "Charlie",
    "Charlotte",
    "Chloe",
    "Claire",
    "Clara",
    "Daisy",
    "Delilah",
    "Eden",
    "Eleanor",
    "Elena",
    "Eliza",
    "Elizabeth",
    "Ella",
    "Ellie",
    "Eloise",
    "Elsie",
    "Emilia",
    "Emily",
    "Emma",
    "Eva",
    "Evelyn",
    "Evie",
    "Florence",
    "Frankie",
    "Freya",
    "Georgia",
    "Grace",
    "Hallie",
    "Hannah",
    "Harlow",
    "Harper",
    "Harriet",
    "Hazel",
    "Imogen",
    "Isabel",
    "Isabella",
    "Isabelle",
    "Isla",
    "Ivy",
    "Jasmine",
    "Lara",
    "Layla",
    "Lily",
    "Lola",
    "Lucy",
    "Luna",
    "Mackenzie",
    "Maddison",
    "Maeve",
    "Maggie",
    "Matilda",
    "Maya",
    "Mia",
    "Mila",
    "Millie",
    "Molly",
    "Olive",
    "Olivia",
    "Penelope",
    "Peyton",
    "Phoebe",
    "Piper",
    "Pippa",
    "Poppy",
    "Quinn",
    "Remi",
    "Rose",
    "Rosie",
    "Ruby",
    "Sadie",
    "Sarah",
    "Savannah",
    "Scarlett",
    "Sienna",
    "Sofia",
    "Sophia",
    "Sophie",
    "Stella",
    "Summer",
    "Violet",
    "Willow",
    "Zara",
    "Zoe"]
    
    let isMale = Bool.random()
    
    var firstName = girlnames.randomElement()!
    if isMale {
        firstName = boynames.randomElement()!
    }
    let surName = surnames.randomElement()!
    
    let totOdds = surName.light + surName.medLight + surName.medium + surName.medDark + surName.dark
    let myOdds = Int.random(in: 0...totOdds)
    var skin = 0
    if myOdds < surName.light {
        skin = 0
    } else if myOdds < surName.light + surName.medLight {
        skin = 1
    } else if myOdds < surName.light + surName.medLight + surName.medium {
        skin = 2
    } else if myOdds < surName.light + surName.medLight + surName.medium + surName.medDark {
        skin = 3
    } else {
        skin = 4
    }

return (firstName, surName.surname, isMale, skin)
}
